spring:
  application:
    name: volksbook
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://simwor.com:3306/volksbook?useUnicode=true&characterEncoding=utf8
    username: rayslee
    password: Libo0614..
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000